### PR TITLE
docs: add static test doc

### PR DESCRIPTION
**Pull request by czyrye**
文档建设和优化：静态测试 https://github.com/Tencent/3TS/issues/36 issue认领。添加了StaticTest.md文档，对case_cntl.cc、sqltest.cc、sql_cntl.cc三个文件进行概述。

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/3TS?pullRequest=47) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/3TS?pullRequest=47) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/3TS?pullRequest=47) it.</sub>

**Review by hldgs — COMMENTED** [review]
if any questions, reply me directly

**Comment by hldgs** [comment]
please transalate your pr title, pr description to english, thanks. And we recommended [format](https://www.conventionalcommits.org/zh-hans/v1.0.0/#%e7%ba%a6%e5%ae%9a%e5%bc%8f%e6%8f%90%e4%ba%a4%e8%a7%84%e8%8c%83) to title your pr.

**Comment by hldgs** [comment]
you can use "docs: add static test doc" as your pr title

**Pull request merged**
