### PR TITLE
docs: add a doc to build 3TS-Coo on ubuntu18.04

### PR DESCRIPTION
**Pull request by gukj-spel**
pr for issue #39 , adddocumentation, introduce how to compile 3TS-Coo in ubuntu18.04.
* The ODBC driver manager uses unixODBC
* The database uses Mysq 8.0.18
* ODBC Driver uses Mysql 8.0.18 odbc-connector

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/3TS?pullRequest=48) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/3TS?pullRequest=48) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/3TS?pullRequest=48) it.</sub>

**Comment by hldgs** [comment]
Hello, I am one of the code reviewers. Can you translate your **pr** title descriptionto English? And we recommend using this [format](https://www.conventionalcommits.org/zh-hans/v1.0.0/#%e7%ba%a6%e5%ae%9a%e5%bc%8f%e6%8f%90%e4%ba%a4%e8%a7%84%e8%8c%83) to title your PR.

**Comment by gukj-spel** [comment]
> Hello, I am one of the code reviewers. Can you translate your **pr** title descriptionto English? And we recommend using this [format](https://www.conventionalcommits.org/zh-hans/v1.0.0/#%e7%ba%a6%e5%ae%9a%e5%bc%8f%e6%8f%90%e4%ba%a4%e8%a7%84%e8%8c%83) to title your PR.

of course, I would like to modify my title

**Review by hldgs — CHANGES_REQUESTED** [review]
if any questions, reply me directly

**Pull request merged**
